# Generated by Django 6.0.3 on 2026-03-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['order', '-date'],
            },
        ),
    ]
