# Generated by Django 6.0.3 on 2026-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icas', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='show_on_contact_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('director', 'Director'), ('faculty', 'Faculty Researcher'), ('researcher', 'Researcher'), ('student', 'Graduate Student')], max_length=20),
        ),
    ]
