# Generated by Django 6.0.3 on 2026-03-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icas', '0003_teammember_department_teammember_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('president', 'President'), ('director', 'Director'), ('faculty', 'Faculty Researcher'), ('researcher', 'Researcher'), ('student', 'Graduate Student')], max_length=20),
        ),
    ]
