# Generated by Django 6.0.3 on 2026-03-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icas', '0004_alter_teammember_designation_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('director', 'Director'), ('faculty', 'Faculty Researcher'), ('researcher', 'Researcher')], max_length=20),
        ),
    ]
