# Generated by Django 6.0.3 on 2026-03-13 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icas', '0005_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='activities', to='icas.teammember'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='icas.event'),
        ),
        migrations.AddField(
            model_name='activity',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='icas.project'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to='icas.teammember'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='icas.project'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_events', to='icas.teammember'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='events', to='icas.project'),
        ),
        migrations.AddField(
            model_name='event',
            name='research_areas',
            field=models.ManyToManyField(blank=True, related_name='events', to='icas.researcharea'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_events',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='icas.event'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='icas.project'),
        ),
        migrations.AddField(
            model_name='news',
            name='related_publications',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='icas.publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='projects', to='icas.partner'),
        ),
        migrations.AddField(
            model_name='project',
            name='research_areas',
            field=models.ManyToManyField(blank=True, related_name='projects', to='icas.researcharea'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='projects', to='icas.teammember'),
        ),
        migrations.AddField(
            model_name='publication',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='publications', to='icas.project'),
        ),
        migrations.AddField(
            model_name='publication',
            name='research_areas',
            field=models.ManyToManyField(blank=True, related_name='publications', to='icas.researcharea'),
        ),
        migrations.AddField(
            model_name='publication',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='publications', to='icas.teammember'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='research_areas',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='icas.researcharea'),
        ),
    ]
